# Generated by Django 4.1.3 on 2022-11-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.IntegerField(db_column='classroom_ID', primary_key=True, serialize=False)),
                ('building_name', models.CharField(blank=True, max_length=225, null=True)),
                ('class_capacity', models.IntegerField(blank=True, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(db_column='course_ID', primary_key=True, serialize=False)),
                ('instructor_id', models.IntegerField(db_column='instructor_ID')),
                ('department_id', models.IntegerField(db_column='department_ID')),
                ('course_name', models.CharField(blank=True, max_length=225, null=True)),
                ('department_name', models.CharField(blank=True, max_length=225, null=True)),
                ('credit_hours', models.IntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, max_length=225, null=True)),
                ('batch_year', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(db_column='department_ID', primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=225, null=True)),
                ('building_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.IntegerField(db_column='instructor_ID', primary_key=True, serialize=False)),
                ('department_id', models.IntegerField(db_column='department_ID')),
                ('instructor_name', models.CharField(blank=True, max_length=225, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('instructor_office_addr', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prereqs',
            fields=[
                ('course_id', models.IntegerField(db_column='course_ID', primary_key=True, serialize=False)),
                ('prereqs_id', models.IntegerField(db_column='prereqs_ID')),
                ('prereqs_names', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'prereqs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.IntegerField(db_column='section_ID', primary_key=True, serialize=False)),
                ('instructor_id', models.IntegerField(db_column='instructor_ID')),
                ('course_id', models.IntegerField(db_column='course_ID')),
                ('batch_year', models.TextField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, max_length=225, null=True)),
                ('number_students', models.IntegerField(blank=True, null=True)),
                ('section_capacity', models.IntegerField(blank=True, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(db_column='student_ID', primary_key=True, serialize=False)),
                ('department_id', models.IntegerField(db_column='department_ID')),
                ('student_name', models.CharField(blank=True, max_length=225, null=True)),
                ('batch_year', models.TextField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=225, null=True)),
                ('total_credithours', models.IntegerField(blank=True, null=True)),
                ('student_semester', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('timeslot_id', models.IntegerField(db_column='timeslot_ID', primary_key=True, serialize=False)),
                ('course_id', models.IntegerField(db_column='course_ID')),
                ('classroom_id', models.IntegerField(db_column='classroom_ID')),
                ('section_id', models.IntegerField(db_column='section_ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeslot',
                'managed': False,
            },
        ),
    ]
