# Generated by Django 4.1.3 on 2022-11-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_delete_members_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
