# Generated by Django 4.1.3 on 2022-11-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course_id',
            new_name='course_ID',
        ),
    ]
