# Generated by Django 4.1.3 on 2022-11-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_course_id_user_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
