# Generated by Django 4.1.3 on 2022-12-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course_ID',
            new_name='section_ID',
        ),
    ]
