# Generated by Django 4.1.3 on 2022-12-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_dep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dep',
            options={'managed': False},
        ),
    ]
