# Generated by Django 4.1.3 on 2022-12-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_dep_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dep',
            table='Dep',
        ),
    ]
